### ISSUE TITLE
JWT Middleware

### ISSUE THREAD

**Issue by milesje** [seanpmaxwell/overnight#69]
version 1.1.19 causes an error.

```
\node_modules\express-jwt\lib\index.js:22
  if (!options.algorithms) throw new Error('algorithms should be set');
                                 ^
Error: algorithms should be set
    at module.exports (\node_modules\express-jwt\lib\index.js:22:34)
    at Function.JwtManager.setupMiddleware (\node_modules\@overnightjs\jwt\lib\JwtManager.js:42:16)
    at JwtManager.get [as middleware] (\node_modules\@overnightjs\jwt\lib\JwtManager.js:32:31)
    at Object.<anonymous> (\src\controllers\ParentController.ts:11:26)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Module.m._compile (\node_modules\ts-node\src\index.ts:1043:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Object.require.extensions.<computed> [as .ts] (\node_modules\ts-node\src\index.ts:1046:12)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
```

**Comment by seanpmaxwell** [comment]
fixed please see version 1.2. Sorry for late response.
